# Generated by Django 3.2.9 on 2021-12-05 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_userprofile_default_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='default_full_name',
            field=models.CharField(max_length=40),
        ),
    ]
