# Generated by Django 3.2.9 on 2022-02-05 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_review_post_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-post_date']},
        ),
    ]
